baseurl = "https://willianba.github.io/"
enforce_ssl = "www.willianba.github.io"
languageCode = "pt-br"
defaultContentLanguage = "br"
title = "Willian Bandeira Alves"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[permalinks]
  post = "/:day/:month/:year/:slug"

[params]
  avatar = "profile.jpg"
  author = "Willian Bandeira Alves"
  description = "Site Pessoal - Willian Alves"

[params.resume]
  author = "Willian Bandeira Alves"
  title = "Currículo - Willian Bandeira Alves"
  description = "Currículo Willian Alves"
  avatar = "profile.png"
  email = "wba.alves@gmail.com"
  email_full = "mailto:wba.alves@gmail.com"
  website = "willianba.github.io/"
  website_full = "https://willianba.github.io/"
  github = "willianba"
  linkedin = "willianba"
  tel = "+55 51 984469967"
  tel_full = "+5551984469967"
  city = "Gravataí, RS"
  country = "Brasil"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Email       = "wba.alves@gmail.com"
  Github      = "willianba"
  LinkedIn    = "willianba"
  Instagram   = "wbaalves"

## Main Menu
[[menu.main]]
  name = "currículo"
  identifier = "curriculo"
  weight = 300
  url = "/curriculo/"

[Languages]
[Languages.br]
